### ISSUE TITLE
Homework: Unit 4 - Day 17

### ISSUE THREAD

**Issue by tfbkny** [dreikanter/ruby-bookmarks#36]
Homework: (https://github.com/tfbkny/pluto/tree/master/u4-ruby-on-rails/d17-ruby-slippers/student/classnotes/homework)

Complete 1~6
Comfortability: 5
Wins: we finished it :)
Challenges: Wines (finding a way to remove entry from array), last names (getting the last name in the array of student names)

**Comment by dreikanter** [comment]
Are you sure this is the right repo for this issue?

**Comment by MaicolBen** [comment]
haha you should close this issue
