### ISSUE TITLE
Academic writing on the Ruby programming language

### ISSUE THREAD

**Issue by oshanz** [dreikanter/ruby-bookmarks#57]
http://rubybib.org/

 On this page we list research projects using Ruby and peer-reviewed papers and articles that cover Ruby implementation or use Ruby, including alternative implementations such as JRuby.

**Comment by oshanz** [comment]
what is the contribution procedure here? shall I create a pull request?

**Comment by dreikanter** [comment]
Yes, a pull request will do.
