### ISSUE TITLE
Create a script to determine broken links

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/ruby-bookmarks#70]
Requirements:

- Check each link in the `README.md` file, and dump the list of obsolete URLs (with HTTP status is 40*, 50*) to stdio.
- Nice to have feature: CLI option to delete obsolete bookmarks from `README.md`.
- The script should be implemented with Ruby or JS.
- No dependencies, if possible.

**Comment by GaganGupta19** [comment]
Can I work on the first point?

**Comment by dreikanter** [comment]
Sure, thank you

**Comment by GaganGupta19** [comment]
Submitted PR #74 for 1st point. Kindly have a look :)
